### ISSUE TITLE
Type Error when i run cf-to-tf  

### ISSUE THREAD

**Issue by oomartins** [humanmade/cf-to-tf#25]
I have a CFormation config file on my local directory in the path below. When i try to use cf-to-tf to convert using the command below. I get the below error message. 

cf-to-tf --stack - config < /home/Username/Desktop/Test

TypeError: Cannot read property '0' of undefined
    at getStack.then.result (/usr/local/lib/node_modules/@humanmade/cf-to-tf/index.js:47:54)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by yashwanth-l** [comment]
same issue exists - if I use the cf template provided by AWS for Cognito Backups
