### ISSUE TITLE
\'stackName\' failed to satisfy constraint

### ISSUE THREAD

**Issue by grebois** [humanmade/cf-to-tf#5]
```
$ cf-to-tf -s https://aws-quickstart.s3.amazonaws.com/quickstart-atlassian-jira/templates/JiraDataCenter.template config
{ ValidationError: 1 validation error detected: Value 'https://aws-quickstart.s3.amazonaws.com/quickstart-atlassian-jira/templates/JiraDataCenter.template' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
    at Request.extractError (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
  message: '1 validation error detected: Value \'https://aws-quickstart.s3.amazonaws.com/quickstart-atlassian-jira/templates/JiraDataCenter.template\' at \'stackName\' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*',
  code: 'ValidationError',
  time: 2018-09-06T12:28:27.013Z,
  requestId: '5ace66d9-b1d0-11e8-b8e6-6f4fd45d5ff4',
  statusCode: 400,
  retryable: false,
  retryDelay: 66.58297130778628 }
```

**Comment by paulogcrio** [comment]
I have same error. Any solutions?
