### ISSUE TITLE
JSON Parsing Error...?

### ISSUE THREAD

**Issue by LucasPanology** [humanmade/cf-to-tf#8]
Running the comand `cf-to-tf --stack /home/Username/Desktop/Test config | json2hcl | cf-to-tf clean-hcl | terraform fmt -` 

getting the error `Error running fmt: In <standard input>: key 'illegal' expected start of object ('{') or assignment ('=')`

Shortening the first command to `cf-to-tf --stack /home/Username/Desktop/Test config | json2hcl | cf-to-tf clean-hcl`

I get the error  `unable to parse JSON: 1:13: illegal char illegal`

Note: the file `/home/Username/Desktop/Test` is the Demo Cloudformation stack in README.md

**Comment by zackse** [comment]
What is the output from `cf-to-tf --stack /home/Username/Desktop/Test config` ?

**Comment by zackse** [comment]
Given a stack name parameter, the program will attempt to pull the configuration from AWS (i.e., the argument is not a path). To use a local file, try passing its contents to standard input:

```sh
cf-to-tf --stack - config < /home/Username/Desktop/Test
```

**Comment by LucasPanology** [comment]
Those recommended changes solved the problem I was getting running this against the example template.

**Comment by ASethi93** [comment]
Hi i am having an error, i have set the profile with the region it still shows this error cf-to-tf -s LogStack state | tee terraform.tfstate
Error [ConfigError]: Missing region in config
    at Request.VALIDATE_REGION (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/event_listeners.js:92:45)
    at Request.callListeners (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/config.js:379:7)
    at /usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/config.js:397:9
    at SharedIniFileCredentials.get (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/config.js:391:24)
    at Config.getCredentials (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/config.js:411:9)
    at Request.VALIDATE_CREDENTIALS (/usr/local/lib/node_modules/@humanmade/cf-to-tf/node_modules/aws-sdk/lib/event_listeners.js:81:26) {
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2020-02-12T17:36:35.904Z
}
